name: Deploy Examples to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy build output to examples folder
        run: |
          cp -r dist/* examples/assets/

      - name: Prepare Pages output
        run: |
          mkdir -p output
          cp -r examples/* output/

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages